# Generated by Django 5.0.7 on 2024-07-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.CharField(verbose_name='№ п/п в 804 приказе')),
                ('name_804', models.CharField(verbose_name='Наименование в 804 приказе')),
                ('name_provider', models.CharField(verbose_name='Наименование у поставщика')),
                ('provider', models.CharField(verbose_name='Поставщик')),
                ('cost', models.IntegerField(verbose_name='Стоимость')),
                ('size', models.CharField(blank=True, null=True, verbose_name='Размер')),
                ('article', models.CharField(blank=True, null=True, verbose_name='Артикул')),
                ('link', models.CharField(blank=True, null=True, verbose_name='Ссылка на товар у поставщика')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Фото (ссылка)')),
            ],
            options={
                'verbose_name_plural': 'Главная',
                'db_table': 'Main',
                'ordering': ['num'],
            },
        ),
    ]
